template_path: templates/task-role.yaml

parameters:
  ProjectStack: {{ var.ProjectStack }}
  ServiceName: {{ var.MicroserviceName }}
  Environment: {{ var.LocalEnvShortName }}
  AssetInsightId: "{{ var.AssetInsightId }}"
  FinancialIdentifier: "{{ var.FinancialIdentifier }}"
  ResourceOwner: {{ var.ResourceOwner }}
  EnvironmentType: {{ var.LocalEnvFullName }}
  RegionShortName: {{ var.RegionShortName }}
  AccountId: "{{ var.NonProdAccountId }}"

stack_tags:
  "tr:financial-identifier": "{{ var.FinancialIdentifier }}"
  "tr:application-asset-insight-id": "{{ var.AssetInsightId }}"
  "tr:environment-type": {{ var.LocalEnvFullName }}
  "tr:resource-owner": {{ var.ResourceOwner }}
