template_path: templates/cloudwatch-log-group.yaml

parameters:
  ContainerName: {{ var.MicroserviceName }}
  ProjectStack: {{ var.ProjectStack }}
  Environment: {{ var.ProdEnvShortName }}
  LogType: "datadog"
  AssetInsightId: "{{ var.AssetInsightId }}"

stack_tags:
  "tr:financial-identifier": "{{ var.FinancialIdentifier }}"
  "tr:application-asset-insight-id": "{{ var.AssetInsightId }}"
  "tr:environment-type": {{ var.ProdEnvFullName }}
  "tr:resource-owner": {{ var.ResourceOwner }}